### ISSUE TITLE
token_level.py  

### ISSUE THREAD

**Issue by xiatingyu** [Blue-Raincoat/SelectIT#1]
Thanks for your code, I want to know the meaning of 29896, 29906, 29941, 29946, 29945 in token_level.py  
```
for index in range(1):
    tmp_res = [float(softmax_logits[index][29896]), float(softmax_logits[index][29906]),
               float(softmax_logits[index][29941]), float(softmax_logits[index][29946]),
               float(softmax_logits[index][29945])]
    pro.append(tmp_res)
```
If those numbers are relatated with the model? If I want to use Qwen1.5 how should I change the numbers?
Thank you.

**Comment by xiatingyu** [comment]
I check the tokenizer.json of LLama2, I think I know the meaning of the numbers.

**Comment by simplew2011** [comment]
mean string '1-5'
