### ISSUE TITLE
SelectIT最终数据选择策略

### ISSUE THREAD

**Issue by xiatingyu** [Blue-Raincoat/SelectIT#2]
你好，请问如果想同时利用token, sentence, model level来筛选数据应该如何操作？

token level， sentence level 和model level最后都会得到 number=输入数据*proportion的子集，那么最终的数据是这三个子集取交集呢？还是在token level筛选出一部分数据以后，这部分数据作为sentence level的输入继续筛选，以此类推呢？还是说token sentence model level都给出一个分数，最后三个分数取平均再按照大小筛选呢？

**Comment by xinxinxing** [comment]
Based on the  SelectIT paper, we know that the three different levels of data selection strategies are progressive. The sentence-level data selection strategy is based on the token-level data selection strategy, and the model-level data selection strategy is based on the sentence-level data selection strategy. Therefore, if you want to simultaneously utilize the token, sentence, and model-level strategies for data selection, you only need to run the code for Model-level Self-Reflection.

**Comment by xiatingyu** [comment]
Thank you for your response.
