### ISSUE TITLE
Could you provide the Selective Alpaca datasets?

### ISSUE THREAD

**Issue by xiatingyu** [Blue-Raincoat/SelectIT#3]
I'm sorry that I can not reproduce the sentence IT results, and could you provide the Selective Alpaca datasets? 

I want to know if the selected data is same with you.

**Comment by xinxinxing** [comment]
Thank you for your suggestion. We have open-sourced Selective Alpaca on Hugging Face, called Selective_Alpaca. You can find it at https://huggingface.co/datasets/liangxin/Selective_Alpaca.

Secondly, the data  you selected by the sentence level data selection strategy is not consistent with Selective_Alpaca, which also uses the model level data selection. This discrepancy might be the reason for the difference in experimental results.

Lastly, please use the scripts we provided for model training and testing to ensure consistency with the results in the paper.

**Comment by xiatingyu** [comment]
Thank you for your data and your response.
